stages:
  - build
  - deploy


Build:
  stage: build
  only:
  - develop
  image: spikerlabs/scala-sbt
  script:
    - sbt assembly


Deploy:
  stage: deploy
  only:
  - develop
  image: jimmyadaro/gitlab-ci-cd:latest
  script:
    - docker login registry.gitlab.com
    - docker build -t wangxisea/bionlp:latest .
    - docker push wangxisea/bionlp:latest
