stages:
  - build
  - deploy


Build:
  stage: build
  only:
  - develop
  image: spikerlabs/scala-sbt
  script:
    - apk add --no-cache bash git openssh
    - cd /opt
    - git clone https://gitlab.com/wangxisea/${CI_PROJECT_PATH}.git
    - cd ${CI_PROJECT_NAME}
    - sbt assembly


Deploy:
  stage: deploy
  only:
  - develop
  script:
    - docker build -t wangxisea/bionlp:latest .
    - docker push wangxisea/bionlp:latest
