stages:
  - build
  - deploy


Build:
  stage: build
  only:
  - develop
  image: spikerlabs/scala-sbt
  script:
    - sbt assembly


Deploy:
  stage: deploy
  only:
  - develop
  image: docker:latest
  services:
  - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t registry.gitlab.com/wangxisea/spark-lda-biomedical-text .
    - docker login -u $cr_username -p $cr_password registry.gitlab.com
    - docker push registry.gitlab.com/wangxisea/spark-lda-biomedical-text
