stages:
  - build
  - deploy


#Build:
#  stage: build
#  only:
#  - develop
#  image: spikerlabs/scala-sbt
#  script:
#    - sbt assembly


Deploy:
  stage: deploy
  only:
  - develop
  image: docker:latest
  script:
    - docker build -t wangxisea/bionlp:latest .
    - docker login -u $cr_username -p $cr_password registry.gitlab.com
    - docker push wangxisea/bionlp:latest
