stages:
  - build
  - deploy


#Build:
#  stage: build
#  only:
#  - develop
#  image: spikerlabs/scala-sbt
#  script:
#    - sbt assembly


Deploy:
  stage: deploy
  only:
  - develop
  image: docker: git
  script:
    - docker login registry.gitlab.com --username ${cr_username} --password ${cr_password}
    - docker build -t wangxisea/bionlp:latest .
    - docker push wangxisea/bionlp:latest
